#! /bin/bash 

    alias ls="ls --color=auto --group-directories-first"
    alias la="ls -a"
    alias shutdown="shutdown -h now"
    alias restart="xrdb $HOME/.Xresources"
    alias rst="restart"
    alias pt="setxkbmap -model abnt2 -layout br -variant abnt2"
    alias en="setxkbmap -layout us -variant intl" 
    alias src="source $HOME/.bashrc"
    alias clip="xclip -selection clipboard"
    alias bashrc="vim $HOME/.bashrc"
    alias bashc="vim $CONF/bash/bashrc"
    alias basha="vim $CONF/bash/bashra"
    alias bashf="vim $CONF/bash/bashrf"
    alias bashp="vim $CONF/bash/personal"
    alias basht="vim $CONF/bash/tmp"
    alias vimrc="vim $VIM/vimrc"
    alias vimrk="vim $VIM/vimrk"
    alias vimrp="vim $VIM/vimrp"
## "g" as alias for "git" 
## Note: 
##    completion will work only if added "___git_complete g __git_main"
##    at the end of git completion script
    alias g="git"
    
